# ===============================
# A2优化策略: P2检测头 + Anchor重聚类（小目标优化）
# 该策略针对小目标识别，可提升小目标Recall 8~12%
# ===============================

# —— 数据集与模型路径 ——  
data: ${data_path}            # 数据集配置文件路径  
model: 'yolo11s.pt'           # 推荐使用更大的模型以获得更好的小目标检测性能

# —— 基础训练设置 ——  
epochs: 100                   # 训练轮数
batch: 16                     # 批次大小
imgsz: 896                    # 推荐使用较大尺寸以提高小目标检测效果
device: '0'                   # 训练设备，例如: 0, 0,1,2,3
workers: 8                    # 数据加载线程数

# —— 数据增强与超参数 ——  
mosaic: 1.0                   # 镶嵌增强比例，有助于提升小目标检测
scale: 0.5                    # 缩放增强，增加输入多样性

# —— A2专用优化参数 ——
add_p2_head: true             # 在Neck顶端添加P2检测头，增强小目标检测能力
anchors_num: 12               # 聚类的anchor数量，小目标场景推荐使用更多的anchor

# 注意事项
# 1. 此配置适用于包含大量小目标的数据集
# 2. P2检测头需要模型支持，部分YOLO版本可能需要修改源码
# 3. 增加anchors_num会提高小目标检测效果，但可能略微增加计算量
# 4. 对于极小目标(≤10像素)，建议使用更大的img_size

# 预设方案参考（实际使用时请直接修改上方相应参数）
# - 标准方案: imgsz=896, batch=16, add_p2_head=true, anchors_num=10, mosaic=1.0
# - 轻量方案: imgsz=640, batch=16, add_p2_head=true, anchors_num=9, mosaic=0.8
# - 极致方案: model='yolo11m.pt', imgsz=1280, batch=8, add_p2_head=true, anchors_num=15, mosaic=1.0, scale=0.7 