# ===============================
# A3优化策略: SIoU损失 & NMS IoU调节（精度优化）
# 该策略通过改进IoU计算方式，可提升mAP@0.5:0.95 3~5%
# ===============================

# —— 数据集与模型路径 ——  
data: ${data_path}            # 数据集配置文件路径  
model: 'yolo11n.pt'           # 模型类型，可选: yolo11n.pt, yolo11s.pt, yolo11m.pt, yolo11l.pt

# —— 基础训练设置 ——  
epochs: 100                   # 训练轮数
batch: 16                     # 批次大小
imgsz: 640                    # 图像尺寸
device: '0'                   # 训练设备，例如: 0, 0,1,2,3
workers: 8                    # 数据加载线程数

# —— A3专用优化参数 ——
iou_loss: 'siou'              # IoU损失类型，可选: ciou, diou, giou, eiou, siou
iou_thres: 0.6                # NMS IoU阈值，推荐值0.6
iou_type: 'giou'              # IoU类型，可选: iou, giou, siou, eiou
conf_thres: 0.25              # 置信度阈值
nms_agnostic: true            # 类别无关的NMS，提高多类别场景下的检测性能

# 注意事项
# 1. 此配置主要优化模型精度，适合需要高精度检测的场景
# 2. SIoU损失可以更好地处理旋转目标和不规则目标
# 3. 不同的IoU设置会影响AP@0.5和AP@0.5:0.95的平衡
# 4. 某些高级IoU设置可能需要模型直接支持，使用前请确认兼容性

# 预设方案参考（实际使用时请直接修改上方相应参数）
# - 标准方案: iou_loss='siou', iou_thres=0.6, iou_type='giou', conf_thres=0.25
# - AP50优先: iou_loss='giou', iou_thres=0.5, iou_type='giou', conf_thres=0.3
# - AP平均值优先: iou_loss='siou', iou_thres=0.65, iou_type='siou', conf_thres=0.2, nms_agnostic=true
# - 密集场景优化: iou_loss='eiou', iou_thres=0.7, iou_type='eiou', conf_thres=0.4, nms_agnostic=true 