# 数据集配置 - TT100K数据集
# 注意：此文件为数据集配置，不需要转换为训练配置格式

path: D:/Code/github_client/graduate-design/traffic-recognition-v2/data-resolve/processed_data/yolo/2/final  # 数据集根目录（绝对路径）
train: train/images  # 训练图像
val: val/images  # 验证图像
test: test/images  # 测试图像

# 类别信息
nc: 68  # 类别数量
names: ['ph5', 'p26', 'pl40', 'pl60', 'pn', 'i5', 'p11', 'pne', 'pcl', 'pl50', 'w55', 'pl5', 'ph4.5', 'pl80', 'w30', 'pg', 'pl30', 'p19', 'i4l', 'i2r', 'pm20', 'pbp', 'p5', 'pl120', 'p13', 'w57', 'ip', 'p10', 'il100', 'il60', 'il90', 'pb', 'w59', 'il80', 'pl100', 'ph4', 'pl15', 'p1', 'w21', 'i4', 'p3', 'pl70', 'w32', 'w13', 'i2', 'pr40', 'pm30', 'w63', 'p12', 'p18', 'im', 'pl20', 'p6', 'p27', 'pr30', 'i10', 'p23', 'ps', 'w58', 'p25', 'pl90', 'pbm', 'pm55', 'pm10', 'pr60', 'w22', 'p9', 'pa14'] 